### ISSUE TITLE
certificate validation not performed by default

### ISSUE THREAD

**Issue by marten-seemann** [bifurcation/mint#161]
In order to verify the certificate sent by the peer, it is necessary to set the `mint.Config.AuthCertificate` callback. This is insecure and unexpected (the TLS implementation in the standard library verifies the certificate by default), and undocumented as well.

What is the reason that mint behaves this way? Can we fix this?

**Comment by marten-seemann** [comment]
I just noticed that even by setting `mint.Config.AuthCertificate`, certificate verification doesn't work, because

1. `AuthCertificate` is not copied from the `Config` to the `Caps` in https://github.com/bifurcation/mint/blob/master/conn.go#L641-L654.
2. `AuthCertificate` is not copied from the `Caps` to  the `ClientStateWaitCertCR` in https://github.com/bifurcation/mint/blob/master/client-state-machine.go#L694.

This issue should be classified as **critical**. mint accepts *every* certificate.

@ekr @bifurcation

**Comment by bifurcation** [comment]
Thanks for flagging this.  I will take a stab at it tonight/tomorrow.
