### ISSUE TITLE
Repo cannot be forked

### ISSUE THREAD

**Issue by yaronf** [bifurcation/mint#27]
Because of hardcoded references to the specific GitHub repo, e.g. in mint-client/main.go, to "github.com/bifurcation/mint".

Frankly I don't know how Go solves this issue.

Thanks!

**Comment by bifurcation** [comment]
So this is an issue with the `package main` files, right?  Is it possible to use relative paths there?  E.g., `import "../.."`

**Comment by yaronf** [comment]
Yes. This works for me: `import "../../../mint"`

However you cannot use `go build` to build the client/server then, you need to use `go build main.go`.

**Comment by FiloSottile** [comment]
This is the standard case in Go code. If you fork just to make some changes, you usually fork in place, by changing the git remote but keeping the repo in `$GOPATH/src/github.com/bifurcation/mint`. If instead you are maintaining a fork for others to use, you usually have a commit changing the paths in there.

**Comment by yaronf** [comment]
Thanks for the explanation!
